# Generated by Django 5.0.2 on 2024-02-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xodim',
            old_name='bulim',
            new_name='bulimi',
        ),
    ]
