# Generated by Django 5.0.2 on 2024-02-16 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_bulim_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodim',
            name='bulim',
        ),
        migrations.AddField(
            model_name='bulim',
            name='xodim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.xodim'),
        ),
    ]
