# Generated by Django 5.0.2 on 2024-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_rename_bulim_xodim_bulimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulim',
            name='name',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='ish_turi',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='name',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='xatolar',
            name='name',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
