# Generated by Django 5.0.2 on 2024-03-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Direktor', 'Direktor'), ('Admin', 'Admin'), ('Tekshiruvchi', 'Tekshiruvchi'), ('Bulim', 'Bulim')], default='Tekshiruvchi', max_length=12),
        ),
    ]
