# Generated by Django 5.0.2 on 2024-02-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Diretor', 'Diretor'), ('Admin', 'Admin'), ('Tekshiruvchi', 'Tekshiruvchi'), ('Bulum', 'Bulum')], default='Tekshiruvchi', max_length=12),
        ),
    ]
